<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>BatteryIntelligence.Analytics</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BatteryIntelligence.Core\BatteryIntelligence.Core.csproj" />
  </ItemGroup>

</Project>
